# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/test-image-embed',
                'doc_host': 'https://tylere.github.io',
                'git_url': 'https://github.com/tylere/test-image-embed',
                'lib_path': 'test_image_embed'},
  'syms': { 'test_image_embed.core': { 'test_image_embed.core.foo': ( 'https://tylere.github.io/core.html#foo',
                                                                      'https://github.com/tylere/test-image-embed/blob/master/test_image_embed/core.py#L7')}}}